#* Universal HTML IDs for the entire project
class UniversalIDs:
    df = "df"
    url = "url"
    logout_btn = "logout-btn"
    header = "header"
    entire_page = "entire-page"
    sidebar = "sidebar"
    sidebar_btn = "sidebar_btn"
    delete_alert = "delete_account_alert"
    delete_btn = "delete_account_btn"

class LoginIDs(UniversalIDs):
    username_field = "username-field"
    username_cache = "username-cache"
    password_field = "password-field"
    password_cache = "password-cache"
    remember_me = "remember-me"
    login_btn = "login-btn"
    login_redirect = "login-redirect"
    status = "status-login"

class SignupIDs(UniversalIDs):
    username_field = "username-field-signup"
    password_field = "password-field-signup"
    confirm_password_field = "confirm-password-field-signup"
    signup_btn = "signup-btn"
    signup_redirect = "signup-redirect"
    status = "status-signup"

class MapIDs(UniversalIDs):
    cats = "dropdown-cats-map"
    toggle_cats = "toggle-cats-map"
    types = "dropdown-types-map"
    toggle_types = "toggle-types-map"
    map = "aladin-lite-map"
    radio_image = "radio-image-map"
    img_target = "img-target-map"
    survey = "survey-map"
    auto_fov = "auto-fov-map"
    pixels = "pixels-map"
    contrast = "contrast-map"
    brightness = "brightness-map"
    get_image = "get-image-map"
    cat_upload = "cat-upload-map"
    opts_upload = "options-upload-map"
    rad_upload = "rad-map"
    decd_upload = "decd_map"
    type_upload = "type-map"
    btn_upload = "btn-upload-map"
    cat_dump = "cat-dump-map"
    delete_cats = "delete-cat-map"
    delete_btn = "delete-btn-map"
    radio_store = "radio-store-map"
    table_upload = "table-upload-map"
    table_title = "table-title-map"
    table_timestamp = "table-timestamp-map"

class AnalysisIDs(UniversalIDs):
    cats = "dropdown-cats-analysis"
    log_x = "log-x-analysis"
    log_y = "log-y-analysis"
    distance_graph = "distance-graph-analysis"
    log_x_snap2 = "log-x-snap2-analysis"
    log_y_snap2 = "log-y-snap2-analysis"
    snapshot_0002 = "snapshot-0002-analysis"
    ceiling = "ceiling-analysis"
    steps = "steps-analysis"
    process = "process-analysis"
    process_interval = "process-interval-analysis"
    progress_bar = "progress-bar-analysis"
    progress_bar_div = "progress-bar-div-analysis"
    type_graph = "type-graph-analysis"
    sunburst = "sunburst-analysis"
    venn_1 = "venn-1-analysis"
    venn_2 = "venn-2-analysis"
    venn_input = "venn-input-analysis"
    snapshot_002 = "snapshot-002-analysis"
    venn_text = "venn-text-analysis"
    dummy = "dummy-analysis"
    cancel = "cancel_btn_analysis"
    heatmap = "heatmap-analysis"
    heatmap_input = "heatmap-input-analysis"
    log_heatmap = "log-heatmap-analysis"
    sim_cat = "sim-cat-analysis"

class DownloadsIDs(UniversalIDs):
    toggle_all_cats = "toggle-all-cats-downloads"
    toggle_all_types = "toggle-all-types-downloads"
    cats = "dropdown-cats-downloads"
    types = "dropdown-types-downloads"
    include_images = "include-images-downloads"
    image_limit = "image-limit-downloads"
    surveys = "dropdown-surveys-downloads"
    remove_duplicates = "remove-duplicates-downloads"
    threshold = "threshold-downloads"
    priority = "priority-downloads"
    num_of_sources = "num-of-sources-downloads"
    download = "download-downloads"
    download_btn = "download-btn-downloads"
    failed = "failed-downloads"
    progress = "progress-downloads"
    progress_interval = "progress-interval-downloads"
    progress_bar_center = "progress-bar-center-downloads"
    dummy = "dummy-downloads"
    cancel = "cancel_btn_downloads"
    status = "status-downloads"